apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-resource-driver-kubelet-plugin
  namespace: intel-gpu-resource-driver
spec:
  template:
    spec:
      initContainers:
      - name: device-faker
        # 'Always' policy makes it a sideCar container with longer lifecycle,
        # allowing it to be terminated last
        # https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#termination-with-sidecars
        # which allows proper fake root cleanup.
        restartPolicy: Always
        # TODO: switch to CI image when public CI is in place
        image: registry.local/intel-device-faker:v0.5.0
        imagePullPolicy: Always
        command: ["/device-faker", "gpu", "-t", "/opt/templates/gpu-template.json", "-r", "-d", "/tmp/gpu-fake-root", "-c", "-p"]
        volumeMounts:
        - name: gpu-fake-root
          mountPath: /tmp/gpu-fake-root
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
            add:  [ "MKNOD" ]
      containers:
      - name: kubelet-plugin
        command: ["/kubelet-gpu-plugin", "-v", "5"]
        # TODO: change to :devel when public CI is in place
        image: ghcr.io/intel/intel-resource-drivers-for-kubernetes/intel-gpu-resource-driver:devel
        # TODO: pull policy is needed when :devel is used instead of :latest
        imagePullPolicy: Always
        env:
        - name: SYSFS_ROOT
          value: "/tmp/gpu-fake-root/sysfs"
        - name: DEVFS_ROOT
          value: "/tmp/gpu-fake-root/dev"
        # Host dir for system's dynamic CDI dir. Containerd & CRI-O default value.
        - name: CDI_ROOT
          value: "/var/run/cdi"
        volumeMounts:
        - name: gpu-fake-root
          mountPath: /tmp/gpu-fake-root/sysfs
          subPath: sysfs
        - name: gpu-fake-root
          mountPath: /tmp/gpu-fake-root/dev
          subPath: dev
        # Host dir for system's dynamic CDI dir. Containerd & CRI-O default value.
        - name: dynamic-cdi
          mountPath: /var/run/cdi
      volumes:
      - name: gpu-fake-root
        hostPath:
          path: /tmp/gpu-fake-root
      # Host dir for system's dynamic CDI dir. Containerd & CRI-O default value.
      - name: dynamic-cdi
        hostPath:
          path: /var/run/cdi

