apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: claim1
  namespace: intel-gpu-resource-driver
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.intel.com
