apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:intel-gaudi-resource-driver
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - intel-gaudi-resource-driver
  resources:
  - securitycontextconstraints
  verbs:
  - use
