apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:intel-qat-resource-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:intel-qat-resource-driver
subjects:
- kind: ServiceAccount
  name: intel-qat-resource-driver-service-account
  namespace: intel-qat-resource-driver
