apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gaudi-resource-driver-kubelet-plugin
  namespace: intel-gaudi-resource-driver
spec:
  template:
    spec:
      initContainers:
      - name: device-faker
        # 'Always' policy makes it a sideCar container with longer lifecycle,
        # allowing it to be terminated last
        # https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#termination-with-sidecars
        # which allows proper fake root cleanup.
        restartPolicy: Always
        image: ger-is-registry.caas.intel.com/dgpu-orchestration/intel-device-faker:v0.2.0
        imagePullPolicy: Always
        command: ["/device-faker", "gaudi", "-t", "/opt/templates/gaudi-template.json", "-r", "-d", "/tmp/fake-root", "-c"]
        volumeMounts:
        - name: fake-root
          mountPath: /tmp/fake-root
        securityContext:
          privileged: true
          runAsUser: 0
      containers:
      - name: kubelet-plugin
        # `-m` is removed because there is no real HW and HLML lib.
        # `-v 5` is added for more verbose logging.
        command: ["/kubelet-gaudi-plugin", "-v", "5"]
        env:
        - name: SYSFS_ROOT
          value: "/fake-sysfs"
        volumeMounts:
        - name: fake-root
          mountPath: /fake-sysfs
          subPath: sysfs
        - name: fake-root
          mountPath: /fake-dev/dri
          subPath: dev/dri
        - name: fake-root
          mountPath: /fake-cdi
          subPath: cdi
        securityContext:
          privileged: false
      volumes:
      - name: fake-root
        emptyDir: {}
